version: '3.7'

services:
  backend:
    build: ./app
    command: gunicorn daan.wsgi:application --bind 0.0.0.0:8000
    image: cibbie
    container_name: cibbie-backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    volumes:
      - ./app:/app/base
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    networks:
      - cibbie-backend
networks:
  daan-backend:
    driver: bridge